[package]
name = "ray-tracer"
version = "0.1.0"
authors = ["Emilio Cobos √Ålvarez <emilio@crisal.io>"]

[workspace]
members = [
  ".",
  "tracer",
]

[dependencies]
euclid = "*"
glutin = "*"
gleam = "*"
libc = "*"
tracer = { path = "tracer" }
